get_voices:
  name: Get Voices
  description: Retrieve all available voices from ElevenLabs API with optional filtering
  fields:
    voice_type:
      name: Voice Type
      description: Filter voices by type/category
      required: false
      example: "premade"
      selector:
        select:
          options:
            - "premade"
            - "cloned"
            - "generated"
            - "professional"
    search_text:
      name: Search Text
      description: Search for voices by name, description, or labels
      required: false
      example: "british"
      selector:
        text: