get_voices:
  name: Get Voices
  description: Retrieve all available voices from ElevenLabs API with optional filtering
  fields:
    voice_type:
      name: Voice Type
      description: Filter voices by type/category
      required: false
      example: "premade"
      selector:
        select:
          options:
            - "premade"
            - "cloned"
            - "generated"
            - "professional"
    search_text:
      name: Search Text
      description: Search for voices by name, description, or labels
      required: false
      example: "british"
      selector:
        text:

save_voice_profile:
  name: Save Voice Profile
  description: Save a voice profile with ElevenLabs TTS settings for easy reuse
  fields:
    profile_name:
      name: Profile Name
      description: A unique name for this voice profile (e.g., 'Gary', 'Narrator')
      required: true
      example: "Gary"
      selector:
        text:
    voice:
      name: Voice ID
      description: ElevenLabs Voice ID (use the 'Get Voices' service to find available voice IDs)
      required: true
      example: "21m00Tcm4TlvDq8ikWAM"
      selector:
        text:
    model_id:
      name: Model
      description: ElevenLabs model to use (e.g., eleven_turbo_v2_5, eleven_multilingual_v2)
      required: false
      example: "eleven_turbo_v2_5"
      selector:
        text:
    stability:
      name: Stability
      description: Voice stability - lower values add more variability (0.0-1.0)
      required: false
      example: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    similarity_boost:
      name: Similarity Boost
      description: How closely to match the original voice - higher is more similar (0.0-1.0)
      required: false
      example: 0.75
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    style:
      name: Style
      description: Style exaggeration - higher values are more expressive (0.0-1.0)
      required: false
      example: 0.0
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    speed:
      name: Speed
      description: Speech speed multiplier - 1.0 is normal speed (0.25-4.0)
      required: false
      example: 1.0
      selector:
        number:
          min: 0.25
          max: 4.0
          step: 0.05
    use_speaker_boost:
      name: Speaker Boost
      description: Enhance speaker clarity and reduce background noise
      required: false
      example: true
      selector:
        boolean: